import "server-only";

import type { TicketDetailDto } from "@/lib/types";

function maskEmail(email: string) {
  const [name, domain] = email.split("@");
  return `${name.slice(0, 2)}***@${domain}`;
}

export async function sendApprovedReply(ticket: TicketDetailDto, draftReply: string) {
  const apiKey = process.env.RESEND_API_KEY;
  const to = process.env.CONTACT_TO_EMAIL ?? "johnvenancio30@gmail.com";
  const from = process.env.RESEND_FROM_EMAIL ?? "ReplyPilot Demo <onboarding@resend.dev>";
  if (!apiKey) {
    return { id: `demo-email-${Date.now()}`, demo: true, deliveredTo: maskEmail(to) };
  }

  const response = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      authorization: `Bearer ${apiKey}`,
      "content-type": "application/json",
    },
    body: JSON.stringify({
      from,
      to: [to],
      reply_to: ticket.email,
      subject: `[ReplyPilot Demo] ${ticket.draftSubject}`,
      text: `Portfolio workflow for ${ticket.name} <${ticket.email}>\nTicket: ${ticket.ticketNumber}\n\nAPPROVED CUSTOMER REPLY\n\n${draftReply}\n\n---\nGenerated by ReplyPilot and approved by a human operator.`,
      headers: { "X-Entity-Ref-ID": ticket.id },
    }),
    signal: AbortSignal.timeout(15_000),
  });
  if (!response.ok) throw new Error(`Email delivery failed with status ${response.status}.`);
  const payload = await response.json();
  return { id: String(payload.id), demo: false, deliveredTo: maskEmail(to) };
}
